export const RoleName = {
  ADMIN: 'ADMIN',
  USUARIO: 'USUARIO',
} as const

export const PermissionSlug = {
  VER_USUARIOS: 'VER_USUARIOS',
  CREAR_USUARIOS: 'CREAR_USUARIOS',
  ACTUALIZAR_USUARIOS: 'ACTUALIZAR_USUARIOS',
  ELIMINAR_USUARIOS: 'ELIMINAR_USUARIOS',
  VER_CLIENTES: 'VER_CLIENTES',
  CREAR_CLIENTES: 'CREAR_CLIENTES',
  ACTUALIZAR_CLIENTES: 'ACTUALIZAR_CLIENTES',
  ELIMINAR_CLIENTES: 'ELIMINAR_CLIENTES',
  VER_PROYECTOS: 'VER_PROYECTOS',
  VER_PROYECTOS_ASIGNADOS: 'VER_PROYECTOS_ASIGNADOS',
  CREAR_PROYECTOS: 'CREAR_PROYECTOS',
  ACTUALIZAR_PROYECTOS: 'ACTUALIZAR_PROYECTOS',
  ELIMINAR_PROYECTOS: 'ELIMINAR_PROYECTOS',
  VER_TAREAS: 'VER_TAREAS',
  CREAR_TAREAS: 'CREAR_TAREAS',
  ACTUALIZAR_TAREAS: 'ACTUALIZAR_TAREAS',
  ELIMINAR_TAREAS: 'ELIMINAR_TAREAS',
} as const